export default {
    OPEN_EDITOR: 'OPEN_EDITOR',
    // Data
    ADD_DATA: 'ADD_DATA',
    SWITCH_DATA: 'SWITCH_DATA',
    UPDATE_DATA: 'UPDATE_DATA',
    DELETE_DATA: 'DELETE_DATA',
    // Exploration
    ENCODING: 'ADD_ENCODING',
    MODIFY_ENCODING: 'MODIFY_ENCODING',
    REMOVE_ENCODING: 'REMOVE_ENCODING',
    // Design
    CONFIGURE_STYLE: 'CONFIGURE_STYLE',
    // Meta
    UNDO_VIS: 'UNDO_VIS',
    REDO_VIS: 'REDO_VIS',
    // Insight
    BOOKMARK: 'BOOKMARK',
    SAVE: 'SAVE',
}