export default {
    OPEN_EDITOR: 'OPEN_EDITOR',
    // Data
    ADD_DATA: 'ADD_DATA',
    SWITCH_DATA: 'SWITCH_DATA',
    UPDATE_DATA: 'UPDATE_DATA',
    DELETE_DATA: 'DELETE_DATA',
    // Exploration
    ENCODING: 'ADD_ENCODING',
    MODIFY_ENCODING: 'MODIFY_ENCODING',
    REMOVE_ENCODING: 'REMOVE_ENCODING',
    // Style
    CONFIGURE_STYLE: 'CONFIGURE_STYLE',
    // Animation
    ADD_CHART_ANIMATION: 'ADD_CHART_ANIMATION',
    MODIFY_CHART_ANIMATION: 'MODIFY_CHART_ANIMATION',
    REMOVE_CHART_ANIMATION: 'REMOVE_CHART_ANIMATION',
    REORDER_CHART_ANIMATION: 'REORDER_CHART_ANIMATION',
    // Meta
    UNDO_VIS: 'UNDO_VIS',
    REDO_VIS: 'REDO_VIS',
    // Insight
    BOOKMARK: 'BOOKMARK',
    SAVE: 'SAVE',
}