export default {
    // Presentation
    PRESENTATION_APPEAR : 'PRESENTATION_APPEAR',
    PRESENTATION_FLYIN : 'PRESENTATION_FLYIN',
    PRESENTATION_FADEIN : 'PRESENTATION_FADEIN',
    PRESENTATION_ZOOM : 'PRESENTATION_ZOOM',
    PRESENTATION_FADE : 'PRESENTATION_FADE',
    // Interpretation
    INTERPRETATION_SCALE : 'INTERPRETATION_SCALE',
    INTERPRETATION_BLINK : 'INTERPRETATION_BLINK',
    // Reasoning
    REASONING_HIGHLIGHT: 'REASONING_HIGHLIGHT',
    REASONING_FILLCOLOR: 'REASONING_FILLCOLOR',
}